import * as THREE from 'three';

const CAMERA_OFFSET_INITIAL = new THREE.Vector3(-5, 2.5, 0);
const CAMERA_OFFSET_SCROLLED = new THREE.Vector3(-5, 2.5, 2.5);

export const CONFIG = {
    DEBUG: true,
    CUBE_SLIDE_DISTANCE: 1.2,
    CUBE_SLIDE_DURATION: 0.1,
    CUBE_FALL_DISTANCE: 36,
    CUBE_FALL_X_OFFSET: 5,
    CUBE_ROTATION_X: Math.PI * 2,
    CUBE_ROTATION_Z: 0,
    CAMERA_FOLLOW_SPEED: 0.05,
    CAMERA_OFFSET_INITIAL,
    CAMERA_OFFSET_SCROLLED,
    CAMERA_OFFSET: CAMERA_OFFSET_INITIAL.clone()
};